---

- name: "tasks: app-common::defaults"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: defaults

- tags: [ always ]
  ansible.builtin.include_role:
    name: zookeeper-docker
    public: true
    defaults_from: zk
    tasks_from: _none_
