---

- name: "tasks: app-common::docker-compose-prepare"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: docker-compose-prepare

- name: "ZooKeeper: flush configuration"
  tags: [ update ]
  ignore_errors: true
  ansible.builtin.command:
    chdir: "{{ app_workdir }}/conf/zookeeper"
    cmd: "find ./ -xdev -mindepth 1 -delete"
