---

- tags: [ install ]
  delegate_to: "{{ zk_first_server }}"
  delegate_facts: true
  run_once: true
  block:

    - name: "tasks: app-common::docker-compose-run"
      ansible.builtin.include_role:
        name: app-common
        tasks_from: docker-compose-run

    - name: "tasks: zk-admin-stat-test"
      ansible.builtin.include_role:
        name: zookeeper-docker
        tasks_from: zk-admin-stat-test
      vars:
        # first server in cluster always reports error
        zk_admin_stat_ignore_error: true

- name: "tasks: app-common::docker-compose-run"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: docker-compose-run
