---

- name: "generate fact: host_addr_type"
  changed_when: false
  ansible.builtin.set_fact:
    host_addr_type: "{{ hostvars[inventory_hostname]['host_addr_type'] | default(host_addr_type) | default('inventory') }}"

- name: "generate fact: host_addr"
  block:

    - when: hostvars[inventory_hostname]['host_addr_type'] == "fqdn"
      changed_when: false
      ansible.builtin.set_fact:
        host_addr: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"

    - when: hostvars[inventory_hostname]['host_addr_type'] == "ipv4"
      changed_when: false
      ansible.builtin.set_fact:
        host_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}"

    - when: hostvars[inventory_hostname]['host_addr_type'] == "inventory"
      changed_when: false
      ansible.builtin.set_fact:
        host_addr: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

- ansible.builtin.meta: flush_handlers

- name: "verify fact: host_addr"
  when: (host_addr is not defined) or (host_addr | string) == ""
  ansible.builtin.fail:
    msg: "host_addr is empty"

- name: "generate fact: zk_server_id"
  changed_when: false
  ansible.builtin.set_fact:
    zk_server_id: "{{ ansible_play_batch.index(inventory_hostname) + 1 }}"

- name: "generate fact: zk_follower_port"
  changed_when: false
  ansible.builtin.set_fact:
    zk_follower_port: "{{ hostvars[inventory_hostname]['zk_follower_port'] | default(zk_follower_port) }}"

- name: "generate fact: zk_election_port"
  changed_when: false
  ansible.builtin.set_fact:
    zk_election_port: "{{ hostvars[inventory_hostname]['zk_election_port'] | default(zk_election_port) }}"

- name: "generate fact: zk_server"
  changed_when: false
  ansible.builtin.set_fact:
    zk_server: "{{ host_addr }}:{{ zk_follower_port }}:{{ zk_election_port }}"

- name: "generate ZooKeeper server list: global"
  changed_when: false
  delegate_to: localhost
  run_once: True
  ansible.builtin.set_fact:
    zk_servers: "{% for item in ansible_play_batch %}{{ hostvars[item]['zk_server'] }},{% endfor %}"

- name: "generate ZooKeeper server list: global"
  changed_when: false
  delegate_to: localhost
  run_once: True
  ansible.builtin.set_fact:
    zk_servers: "{{ ','.join(zk_servers.split(',') | select()) }}"

- name: "generate ZooKeeper server list: per-host"
  changed_when: false
  ansible.builtin.set_fact:
    zk_servers: "{{ zk_servers | replace(zk_server, ':'.join( [ '0.0.0.0', zk_follower_port, zk_election_port ] )) }}"

- name: "generate fact: zk_client_port"
  changed_when: false
  ansible.builtin.set_fact:
    zk_client_port: "{{ hostvars[inventory_hostname]['zk_client_port'] | default(zk_client_port) }}"

- name: "generate fact: zk_host"
  changed_when: false
  ansible.builtin.set_fact:
    zk_host: "{{ host_addr }}:{{ zk_client_port }}"

- name: "generate ZooKeeper host list for ZooKeeper Exporter"
  changed_when: false
  delegate_to: localhost
  run_once: True
  ansible.builtin.set_fact:
    zk_hosts: "{% for item in ansible_play_batch %}{{ hostvars[item]['zk_host'] }},{% endfor %}"

- name: "generate ZooKeeper host list for ZooKeeper Exporter"
  changed_when: false
  delegate_to: localhost
  run_once: True
  ansible.builtin.set_fact:
    zk_hosts: "{{ ','.join(zk_hosts.split(',') | select()) }}"
