---

- name: "tasks: app-common::generate-facts"
  tags: [ always ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: generate-facts

- ansible.builtin.import_tasks:
    file: generate-id.yml

- name: "fact: zk_observer, zk_follower_port, zk_election_port, zk_client_port"
  tags: [ always ]
  changed_when: false
  ansible.builtin.set_fact:
    zk_observer: "{{ hostvars[inventory_hostname]['zk_observer'] | default(zk_observer) }}"
    zk_follower_port: "{{ hostvars[inventory_hostname]['zk_follower_port'] | default(zk_follower_port) }}"
    zk_election_port: "{{ hostvars[inventory_hostname]['zk_election_port'] | default(zk_election_port) }}"
    zk_client_port: "{{ hostvars[inventory_hostname]['zk_client_port'] | default(zk_client_port) }}"

- name: "fact: zk_server_sfx"
  tags: [ always ]
  changed_when: false
  ansible.builtin.set_fact:
    zk_server_sfx: "{% if (zk_observer | bool) %}:observer{% endif %}{% if (zk_use_ids | bool) %}::{{ zk_server_id }}{% endif %}"

- name: "fact: zk_server, zk_connect_host"
  tags: [ always ]
  changed_when: false
  ansible.builtin.set_fact:
    zk_server: "{{ host_addr }}:{{ zk_follower_port }}:{{ zk_election_port }}{{ zk_server_sfx }}"
    zk_connect_host: "{{ host_addr }}:{{ zk_client_port }}"

- name: "fact: zk_servers, zk_connect_hosts"
  tags: [ always ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  ansible.builtin.set_fact:
    zk_servers: "{% for item in ansible_play_batch %}{{ hostvars[item]['zk_server'] }},{% endfor %}"
    zk_connect_hosts: "{% for item in ansible_play_batch %}{{ hostvars[item]['zk_connect_host'] }},{% endfor %}"

- name: "fact: zk_servers, zk_connect_hosts"
  tags: [ always ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  ansible.builtin.set_fact:
    zk_servers: "{{ ','.join(zk_servers.split(',') | select()) }}"
    zk_connect_hosts: "{{ ','.join(zk_connect_hosts.split(',') | select()) }}"
