---

- ansible.builtin.import_tasks:
    file: defaults.yml

- name: "tasks: app-common::check-basic"
  tags: [ always ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: check-basic

- ansible.builtin.import_tasks:
    file: generate-facts.yml

- ansible.builtin.import_tasks:
    file: prepare-local.yml

- name: "tasks: app-common::assemble-docker-compose"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: assemble-docker-compose

- ansible.builtin.import_tasks:
    file: prepare-remote.yml

- ansible.builtin.import_tasks:
    file: docker-compose-prepare.yml

- ansible.builtin.import_tasks:
    file: preseed-remote.yml

- ansible.builtin.import_tasks:
    file: docker-compose-run.yml

- name: "tasks: app-common::docker-compose-verify"
  tags: [ always ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: docker-compose-verify

- name: "output ZooKeeper connect string"
  tags: [ always ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  ansible.builtin.debug:
    msg: "ZooKeeper connect string: {{ zk_connect_hosts }}"
