---

- name: "Docker: early pull images"
  tags: [ install, update ]
  throttle: "{{ (docker_compose_up_throttle | int) }}"
  async: "{{ (docker_compose_timeout | int) }}"
  poll: 5
  with_items:
    - "{{ image_zookeeper }}"
    - "{{ image_zookeeper_exporter }}"
    - "{{ image_jmx_exporter }}"
  ansible.builtin.command:
    cmd: "docker pull {{ item }}"

- name: "tasks: app-common::prepare-remote"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: prepare-remote

- name: "ZooKeeper: create conf & data directories"
  tags: [ install, update ]
  with_items:
    - "{{ app_workdir }}/conf/zookeeper"
    - "{{ app_workdir }}/data/zookeeper"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
    mode: "0750"
