---

- name: "tasks: app-common::prepare-remote"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: app-common
    tasks_from: prepare-remote

- name: "ZooKeeper: create conf & data directories"
  tags: [ install, update ]
  with_items:
    - "{{ app_workdir }}/conf/zookeeper"
    - "{{ app_workdir }}/data/zookeeper"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
    mode: "0750"
