---

- name: "ZooKeeper: flush configuration"
  tags: [ update ]
  ignore_errors: true
  ansible.builtin.command:
    chdir: "{{ app_workdir }}/conf/zookeeper"
    cmd: "find ./ -xdev -mindepth 1 -delete"

- name: "Docker: preseed default ZooKeeper configuration"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: docker
    tasks_from: cmd-run
  vars:
    image: "{{ image_zookeeper }}"
    bare: true
    workdir: "/opt/bitnami/zookeeper/conf"
    volumes:
      - "{{ app_workdir }}/conf/zookeeper:/out"
    cmd: [ "sh", "-c", "cp -nt /out ./* ; exit 0" ]

- name: "ZooKeeper: adjust filesystem"
  tags: [ install, update ]
  ansible.builtin.command:
    chdir: "{{ app_workdir }}"
    cmd: "chown -R {{ app_uid }}:{{ app_gid }} ./conf/zookeeper"
