---

app_name:
app_name_clean: "{{ app_name | regex_replace('(^[^a-zA-Z0-9]+|[^a-zA-Z0-9]+$)', '') | regex_replace('([_.-])+', '\\1') }}"
app_stem: "{{ app_name_clean | regex_replace('[^a-zA-Z0-9_-]+', '-') | regex_replace('-+', '-') }}"
app_rootdir: "/data"
app_workdir: "{{ app_rootdir }}/{{ app_name_clean }}"

# for Ansible host
playbook_tmpdir: "{{ playbook_dir }}/tmp.{{ app_name_clean }}"

app_uid: "10001"
app_gid: "10001"

app_tls_auto: true
app_tls_force: false
app_tls_srcdir: "{{ playbook_dir }}/files/tls"
app_tls_dstdir: "{{ app_workdir }}/tls"

# "inventory" = use "ansible_host" from inventory (default)
# "fqdn"      = use "ansible_fqdn" from host
# "ipv4"      = use default/first IPv4 address from host
# "custom"    = use host attribute "host_addr" from inventory
# host_addr_type: "inventory"
