---

image_registry_docker: docker.io

docker_compose_timeout: 120

docker_compose_up_throttle: "{{ ((ansible_play_batch | count) / 3) + 1 }}"
docker_compose_down_throttle: "{{ ((ansible_play_batch | count) / 3) + 1 }}"

# NB: docker_compose_binary is defined in roles/docker-compose/defaults/docker.yml
docker_compose_cmd_up: "{{ docker_compose_binary }} up --timeout {{ docker_compose_timeout }} --detach"
docker_compose_cmd_down: "{{ docker_compose_binary }} down --timeout {{ docker_compose_timeout }}"
docker_compose_cmd_ps: "{{ docker_compose_binary }} ps --services"
