---

image_tag_zookeeper: "3.8.1-debian-11-r50"
image_tag_zookeeper_exporter: "v0.1.13"
image_tag_jmx_exporter: "0.19.0-debian-11-r0"

image_zookeeper: "{{ image_registry_docker }}/bitnami/zookeeper:{{ image_tag_zookeeper }}"
image_zookeeper_exporter: "{{ image_registry_docker }}/dabealu/zookeeper-exporter:{{ image_tag_zookeeper_exporter }}"
image_jmx_exporter: "{{ image_registry_docker }}/bitnami/jmx-exporter:{{ image_tag_jmx_exporter }}"

# MUST be set on per-host basis
zk_observer: false

zk_use_ids: false

# set to 0 to disable (excessive) checks
zk_sane_first_server_id: 1

zk_4lw_allowed: "srvr,mntr"

zk_client_port: 2181
zk_tls_port: 3181
zk_follower_port: 2888
zk_election_port: 3888

zk_jmx_port: 5557
zk_jmx_exporter_port: 9002
zk_exporter_port: 9091

zk_admin_port: 8080

# internal variables

# keep in sync with files/docker-compose.d/zookeeper.yml.j2
zk_myid_path: "{{ app_workdir }}/data/zookeeper/data/myid"

zk_admin_stat_ignore_error: false
