---

- name: "install ca-certificates"
  tags: [ install ]
  ansible.builtin.apt:
    name: "ca-certificates"
    update_cache: yes

- name: "enumerate extra CA certificates on Ansible host at {{ extra_ca_src_dir }}/"
  tags: [ install, configure ]
  delegate_to: localhost
  run_once: True
  changed_when: false
  ansible.builtin.set_fact:
    extra_ca_files: "{{ extra_ca_src_mask | fileglob }}"

- name: "copy extra CA certificates"
  tags: [ install, configure ]
  when: extra_ca_files is defined and extra_ca_files
  loop: "{{ extra_ca_files }}"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ extra_ca_dst_dir }}/"
    owner: root
    group: root
    mode: "0644"

- name: "update CA certificates"
  tags: [ install, configure ]
  when: extra_ca_files is defined and extra_ca_files
  ansible.builtin.command: "update-ca-certificates"
