---

- name: "verify fact: app_name_clean"
  tags: [ always ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  when: (app_name_clean | string) == ""
  ansible.builtin.fail:
    msg: "app_name_clean is empty"
