---

- name: "Docker Compose: run (with parallel={{ async_throttle | int }})"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: docker-compose
    tasks_from: cmd-up
  vars:
    chdir: "{{ app_workdir }}"
