---

- name: "Docker Compose: verify all services"
  tags: [ always ]
  throttle: "{{ docker_compose_up_throttle | int }}"
  async: "{{ (docker_compose_timeout | int) }}"
  poll: 5
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ app_workdir }}"
    cmd: "{{ docker_compose_cmd_ps }}"
  register: ctx_svc_all
  failed_when: ctx_svc_all.rc != 0

- name: "Docker Compose: verify running services"
  tags: [ always ]
  throttle: "{{ docker_compose_up_throttle | int }}"
  async: "{{ (docker_compose_timeout | int) }}"
  poll: 5
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ app_workdir }}"
    cmd: "{{ docker_compose_cmd_ps }} --status running"
  register: ctx_svc_run
  failed_when: ctx_svc_run.rc != 0

- name: "Docker Compose: compare all vs running services"
  tags: [ always ]
  changed_when: false
  when: (ctx_svc_all.stdout | string) != (ctx_svc_run.stdout | string)
  ansible.builtin.fail:
    msg: "some services are not running!"
