---

- name: "Docker Compose: stop previous installation"
  tags: [ update ]
  ansible.builtin.include_role:
    name: docker-compose
    tasks_from: cmd-down
  vars:
    chdir: "{{ app_workdir }}"

- name: "Docker Compose: create manifest"
  tags: [ install, update ]
  ansible.builtin.template:
    src: "{{ playbook_tmpdir }}/docker-compose.yml.j2"
    dest: "{{ app_workdir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"

- name: "Docker Compose: prepare"
  tags: [ install, update ]
  ansible.builtin.include_role:
    name: docker-compose
    tasks_from: cmd-up
  vars:
    chdir: "{{ app_workdir }}"
    argv: [ "--no-start" ]
