---

- name: "Docker Compose: run (with parallel={{ docker_compose_up_throttle }})"
  tags: [ install, update ]
  throttle: "{{ docker_compose_up_throttle | int }}"
  async: "{{ (docker_compose_timeout | int) }}"
  poll: 15
  ansible.builtin.command:
    chdir: "{{ app_workdir }}"
    cmd: "{{ docker_compose_cmd_up }}"
