---

- tags: [ always ]
  ansible.builtin.import_tasks:
    file: check-basic.yml

- name: "wipe temporary directory for playbook/role files: {{ playbook_tmpdir }}"
  tags: [ install, update ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  ansible.builtin.command:
    argv:
      - "rm"
      - "-rf"
      - "{{ playbook_tmpdir }}"

- name: "create temporary directory for playbook/role files: {{ playbook_tmpdir }}"
  tags: [ install, update ]
  delegate_to: localhost
  run_once: true
  changed_when: false
  ansible.builtin.file:
    path: "{{ playbook_tmpdir }}"
    state: directory
    mode: "0755"

- tags: [ always ]
  ansible.builtin.import_tasks:
    file: preseed-local.yml
  vars:
    preseed_src: "{{ role_path }}/files"
